version: 2
jobs:
  validate-plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/project/account.json
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Validate
          command: terraform validate -var "project-name=$GCP_PROJECT_ID" -var 'vmcount=3' -var "region=$GCP_PROJECT_ZONE" -var 'instance-name=vagrant-build' -var 'subnetwork-region=europe-west1' -var 'network=vagrant-network' -var 'vm_type=n1-standard-2' -var 'os=centos-7-v20180815' -var 'image-name=vagrantimg' -var 'disk-name=vagrantdisk' -var 'disk-size=20'

workflows:
  version: 2
  validate:
    jobs:
      - validate-plan
